function data = exactSolutionMHD

data = struct('f1',@f1, 'f2',@f2, 'u1exact',@u1exact, 'u2exact',@u2exact, 'pexact',@pexact, ...
              'g1',@g1, 'g2',@g2, 'B1exact',@B1exact, 'B2exact',@B2exact);

%% Example 1          
    function r = f1(x,y,t) 
        r = 2*t + 5*y.^4.*(t.^2 + x.^5) + 20*(t.^2 + 1).*(2*y - 1) - 20*y.^3 + (t.^2 + sin(x)).*(cos(x) - cos(y));
    end
    function r = f2(x,y,t)
        r = 2*t + 5*x.^4.*(t.^2 + y.^5) + 2*(t.^2 + 1).*(20*x - 10) - 20*x.^3 - (t.^2 + sin(y)).*(cos(x) - cos(y));
    end
    function r = u1exact(x,y,t)
        r = y.^5 + t.^2;
    end
    function r = u2exact(x,y,t) 
        r = x.^5 + t.^2;
    end
    function r = pexact(x,y,t)
        r = 10*(2*x-1).*(2*y-1).*(1+t.^2);
    end
    function r = g1(x,y,t)
        r = 2*t + sin(y) + cos(y).*(t.^2 + x.^5) - 5*y.^4.*(t.^2 + sin(x));
    end
    function r = g2(x,y,t)
        r = 2*t + sin(x) + cos(x).*(t.^2 + y.^5) - 5*x.^4.*(t.^2 + sin(y));
    end
    function r = B1exact(x,y,t)
        r = t.^2 + sin(y);
    end
    function r = B2exact(x,y,t)
        r = t.^2 + sin(x);
    end

%% Example 2
%     function r = f1(x,y,t) 
%         r = cos(t).*(4*y - 2) - 4*x.^2.*cos(t).*(x - 1).^2.*(y - 1) - ...
%             2*x.^2.*cos(t).*(2*y - 1).*(x - 1).^2 - 4*x.^2.*y.*cos(t).*(x - 1).^2 - ...
%             2*pi*cos(pi*x).*sin(pi*x).*sin(pi*y).^2.*cos(t).^2 - ...
%             2*x.^2.*y.*cos(t).*(2*y - 1).*(y - 1) - 2*y.*cos(t).*(2*y - 1).*(x - 1).^2.*(y - 1) - ...
%             4*x.*y.*cos(t).*(2*x - 2).*(2*y - 1).*(y - 1) - x.^2.*y.*sin(t).*(2*y - 1).*(x - 1).^2.*(y - 1) - ...
%             x.^3.*y.^2.*cos(t).^2.*(2*x - 1).*(x - 1).^3.*(y - 1).^2.*(6*y.^2 - 6*y + 1) + ...
%             2*x.^3.*y.^2.*cos(t).^2.*(2*y - 1).*(x - 1).^2.*(y - 1).*(2*x.^2 - 3*x + 1).*(2*y.^2 - 3*y + 1);
%     end
%     function r = f2(x,y,t)
%         r = cos(t).*(4*x - 2) + 4*y.^2.*cos(t).*(x - 1).*(y - 1).^2 + ...
%             2*y.^2.*cos(t).*(2*x - 1).*(y - 1).^2 + 4*x.*y.^2.*cos(t).*(y - 1).^2 - ...
%             2*pi*cos(pi*y).*sin(pi*x).^2.*sin(pi*y).*cos(t).^2 + 2*x.*y.^2.*cos(t).*(2*x - 1).*(x - 1) + ...
%             2*x.*cos(t).*(2*x - 1).*(x - 1).*(y - 1).^2 + 4*x.*y.*cos(t).*(2*x - 1).*(2*y - 2).*(x - 1) + ...
%             x.*y.^2.*sin(t).*(2*x - 1).*(x - 1).*(y - 1).^2 - x.^2.*y.^3.*cos(t).^2.*(2*y - 1).*(x - 1).^2.*(y - 1).^3.*(6*x.^2 - 6*x + 1) + ...
%             2*x.^2.*y.^3.*cos(t).^2.*(2*x - 1).*(x - 1).*(y - 1).^2.*(2*x.^2 - 3*x + 1).*(2*y.^2 - 3*y + 1);
%     end
%     function r = u1exact(x,y,t)
%         r = x.^2.*(x-1).^2.*y.*(y-1).*(2*y-1).*cos(t);
%     end
%     function r = u2exact(x,y,t) 
%         r = - x.*(x-1).*(2*x-1).*y.^2.*(y-1).^2.*cos(t);
%     end
%     function r = pexact(x,y,t)
%         r = (2*x-1).*(2*y-1).*cos(t);
%     end
%     function r = g1(x,y,t)
%         r = 2*pi^2*cos(pi*y).*sin(pi*x).*cos(t) - cos(pi*y).*sin(pi*x).*sin(t) + ...
%             2*x.^2.*y.*cos(pi*x).*sin(pi*y).*cos(t).^2.*(x - 1).^2.*(y - 1) + ...
%             x.^2.*y.*cos(pi*x).*sin(pi*y).*cos(t).^2.*(2*y - 1).*(x - 1).^2 + ...
%             x.^2.*cos(pi*x).*sin(pi*y).*cos(t).^2.*(2*y - 1).*(x - 1).^2.*(y - 1) - ...
%             x.*y.^2.*cos(pi*y).*sin(pi*x).*cos(t).^2.*(2*x - 1).*(2*y - 2).*(x - 1) - ...
%             2*x.*y.*cos(pi*y).*sin(pi*x).*cos(t).^2.*(2*x - 1).*(x - 1).*(y - 1).^2 + ...
%             pi*x.^2.*y.*cos(pi*x).*cos(pi*y).*cos(t).^2.*(2*y - 1).*(x - 1).^2.*(y - 1) + ...
%             pi*x.*y.^2.*sin(pi*x).*sin(pi*y).*cos(t).^2.*(2*x - 1).*(x - 1).*(y - 1).^2;
%     end
%     function r = g2(x,y,t)
%         r = cos(pi*x).*sin(pi*y).*sin(t) - 2*pi^2*cos(pi*x).*sin(pi*y).*cos(t) + ...
%             2*x.*y.^2.*cos(pi*y).*sin(pi*x).*cos(t).^2.*(x - 1).*(y - 1).^2 + ...
%             x.*y.^2.*cos(pi*y).*sin(pi*x).*cos(t).^2.*(2*x - 1).*(y - 1).^2 + ...
%             y.^2.*cos(pi*y).*sin(pi*x).*cos(t).^2.*(2*x - 1).*(x - 1).*(y - 1).^2 - ...
%             x.^2.*y.*cos(pi*x).*sin(pi*y).*cos(t).^2.*(2*x - 2).*(2*y - 1).*(y - 1) - ...
%             2*x.*y.*cos(pi*x).*sin(pi*y).*cos(t).^2.*(2*y - 1).*(x - 1).^2.*(y - 1) + ...
%             pi*x.*y.^2.*cos(pi*x).*cos(pi*y).*cos(t).^2.*(2*x - 1).*(x - 1).*(y - 1).^2 + ...
%             pi*x.^2.*y.*sin(pi*x).*sin(pi*y).*cos(t).^2.*(2*y - 1).*(x - 1).^2.*(y - 1);
%     end
%     function r = B1exact(x,y,t)
%         r = sin(pi*x).*cos(pi*y).*cos(t);
%     end
%     function r = B2exact(x,y,t)
%         r = - cos(pi*x).*sin(pi*y).*cos(t);
%     end


%% Example 3
%     function r = f1(x,y,t) 
%         r = cos(t).*(4*y - 2) - 4*x.^2.*cos(t).*(x - 1).^2.*(y - 1) - ...
%             2*x.^2.*cos(t).*(2*y - 1).*(x - 1).^2 - 4*x.^2.*y.*cos(t).*(x - 1).^2 - ...
%             2*pi*cos(pi*x).*sin(pi*x).*sin(pi*y).^2.*cos(t).^2 - ...
%             2*x.^2.*y.*cos(t).*(2*y - 1).*(y - 1) - 2*y.*cos(t).*(2*y - 1).*(x - 1).^2.*(y - 1) - ...
%             4*x.*y.*cos(t).*(2*x - 2).*(2*y - 1).*(y - 1) - x.^2.*y.*sin(t).*(2*y - 1).*(x - 1).^2.*(y - 1) - ...
%             x.^3.*y.^2.*cos(t).^2.*(2*x - 1).*(x - 1).^3.*(y - 1).^2.*(6*y.^2 - 6*y + 1) + ...
%             2*x.^3.*y.^2.*cos(t).^2.*(2*y - 1).*(x - 1).^2.*(y - 1).*(2*x.^2 - 3*x + 1).*(2*y.^2 - 3*y + 1);
%     end
%     function r = f2(x,y,t)
%         r = cos(t).*(4*x - 2) + 4*y.^2.*cos(t).*(x - 1).*(y - 1).^2 + ...
%             2*y.^2.*cos(t).*(2*x - 1).*(y - 1).^2 + 4*x.*y.^2.*cos(t).*(y - 1).^2 - ...
%             2*pi*cos(pi*y).*sin(pi*x).^2.*sin(pi*y).*cos(t).^2 + 2*x.*y.^2.*cos(t).*(2*x - 1).*(x - 1) + ...
%             2*x.*cos(t).*(2*x - 1).*(x - 1).*(y - 1).^2 + 4*x.*y.*cos(t).*(2*x - 1).*(2*y - 2).*(x - 1) + ...
%             x.*y.^2.*sin(t).*(2*x - 1).*(x - 1).*(y - 1).^2 - x.^2.*y.^3.*cos(t).^2.*(2*y - 1).*(x - 1).^2.*(y - 1).^3.*(6*x.^2 - 6*x + 1) + ...
%             2*x.^2.*y.^3.*cos(t).^2.*(2*x - 1).*(x - 1).*(y - 1).^2.*(2*x.^2 - 3*x + 1).*(2*y.^2 - 3*y + 1);
%     end
%     function r = u1exact(x,y,t)
%         r = x.^2.*(x-1).^2.*y.*(y-1).*(2*y-1).*cos(t);
%     end
%     function r = u2exact(x,y,t) 
%         r = - x.*(x-1).*(2*x-1).*y.^2.*(y-1).^2.*cos(t);
%     end
%     function r = pexact(x,y,t)
%         r = (2*x-1).*(2*y-1).*cos(t);
%     end
%     function r = g1(x,y,t)
%         r = 2*pi^2*cos(pi*y).*sin(pi*x).*cos(t) - cos(pi*y).*sin(pi*x).*sin(t) + ...
%             2*x.^2.*y.*cos(pi*x).*sin(pi*y).*cos(t).^2.*(x - 1).^2.*(y - 1) + ...
%             x.^2.*y.*cos(pi*x).*sin(pi*y).*cos(t).^2.*(2*y - 1).*(x - 1).^2 + ...
%             x.^2.*cos(pi*x).*sin(pi*y).*cos(t).^2.*(2*y - 1).*(x - 1).^2.*(y - 1) - ...
%             x.*y.^2.*cos(pi*y).*sin(pi*x).*cos(t).^2.*(2*x - 1).*(2*y - 2).*(x - 1) - ...
%             2*x.*y.*cos(pi*y).*sin(pi*x).*cos(t).^2.*(2*x - 1).*(x - 1).*(y - 1).^2 + ...
%             pi*x.^2.*y.*cos(pi*x).*cos(pi*y).*cos(t).^2.*(2*y - 1).*(x - 1).^2.*(y - 1) + ...
%             pi*x.*y.^2.*sin(pi*x).*sin(pi*y).*cos(t).^2.*(2*x - 1).*(x - 1).*(y - 1).^2;
%     end
%     function r = g2(x,y,t)
%         r = cos(pi*x).*sin(pi*y).*sin(t) - 2*pi^2*cos(pi*x).*sin(pi*y).*cos(t) + ...
%             2*x.*y.^2.*cos(pi*y).*sin(pi*x).*cos(t).^2.*(x - 1).*(y - 1).^2 + ...
%             x.*y.^2.*cos(pi*y).*sin(pi*x).*cos(t).^2.*(2*x - 1).*(y - 1).^2 + ...
%             y.^2.*cos(pi*y).*sin(pi*x).*cos(t).^2.*(2*x - 1).*(x - 1).*(y - 1).^2 - ...
%             x.^2.*y.*cos(pi*x).*sin(pi*y).*cos(t).^2.*(2*x - 2).*(2*y - 1).*(y - 1) - ...
%             2*x.*y.*cos(pi*x).*sin(pi*y).*cos(t).^2.*(2*y - 1).*(x - 1).^2.*(y - 1) + ...
%             pi*x.*y.^2.*cos(pi*x).*cos(pi*y).*cos(t).^2.*(2*x - 1).*(x - 1).*(y - 1).^2 + ...
%             pi*x.^2.*y.*sin(pi*x).*sin(pi*y).*cos(t).^2.*(2*y - 1).*(x - 1).^2.*(y - 1);
%     end
%     function r = B1exact(x,y,t)
%         r = sin(pi*x).*cos(pi*y).*cos(t);
%     end
%     function r = B2exact(x,y,t)
%         r = - cos(pi*x).*sin(pi*y).*cos(t);
%     end
end