function data = dataRotation(nu)

%% Exact data
data = struct('f',@f, 'exactu',@exactu, 'exactp',@exactp, 'littlep',@littlep, 'omega',@omega, 'g_D',@exactu, 'diffCo',@diffCo);
t = 3; s = 0.1;

%% Exact data
    function r = exactu(p)
        x = p(:,1); y = p(:,2);
        r(:,1) = s*exp(s*y)/(2*pi*(exp(s)-1)).*sin(2*pi*(exp(s*y)-1)/(exp(s)-1)).* ...
                (1 - cos(2*pi*(exp(t*x)-1)/(exp(t)-1)));
        r(:,2) = - t*exp(t*x)/(2*pi*(exp(t)-1)).*sin(2*pi*(exp(t*x)-1)/(exp(t)-1)).* ...
               (1 - cos(2*pi*(exp(s*y)-1)/(exp(s)-1)));
    end
    function r = littlep(p)
        x = p(:,1); y = p(:,2);
        r = t*s*exp(t*x).*exp(s*y)/((exp(t)-1)*(exp(s)-1)).* ...
            sin(2*pi*(exp(t*x)-1)/(exp(t)-1)).* ...
            sin(2*pi*(exp(s*y)-1)/(exp(s)-1));
    end
    function r = exactp(p)
        pp = littlep(p); vel = exactu(p);
        r = pp + 1/2 * (vel(:,1).*vel(:,1) + vel(:,2).*vel(:,2));
    end
    function r = f(p)
        x = p(:,1); y = p(:,2);
        r(:,1) = nu*((3*s^3*exp(2*s*y).*cos((2*pi*(exp(s*y) - 1))/(exp(s) - 1)).*(cos((2*pi*(exp(t*x) - 1))/(exp(t) - 1)) - 1))/(exp(s) - 1)^2 + ...
            (s^3*exp(s*y).*sin((2*pi*(exp(s*y) - 1))/(exp(s) - 1)).*(cos((2*pi*(exp(t*x) - 1))/(exp(t) - 1)) - 1))/(2*pi*(exp(s) - 1)) - ...
            (2*pi*s^3*exp(3*s*y).*sin((2*pi*(exp(s*y) - 1))/(exp(s) - 1)).*(cos((2*pi*(exp(t*x) - 1))/(exp(t) - 1)) - 1))/(exp(s) - 1)^3) - ...
            nu*((s*t^2*exp(s*y).*exp(t*x).*sin((2*pi*(exp(s*y) - 1))/(exp(s) - 1)).*sin((2*pi*(exp(t*x) - 1))/(exp(t) - 1)))/((exp(s) - 1)*(exp(t) - 1)) + ...
            (2*pi*s*t^2*exp(s*y).*exp(2*t*x).*cos((2*pi*(exp(t*x) - 1))/(exp(t) - 1)).*sin((2*pi*(exp(s*y) - 1))/(exp(s) - 1)))/((exp(s) - 1)*(exp(t) - 1)^2)) + ...
            (t^3*exp(2*t*x).*sin((2*pi*(exp(t*x) - 1))/(exp(t) - 1)).^2.*(cos((2*pi*(exp(s*y) - 1))/(exp(s) - 1)) - 1).^2)/(4*pi^2*(exp(t) - 1)^2) + ...
            (t^3*exp(3*t*x).*cos((2*pi*(exp(t*x) - 1))/(exp(t) - 1)).*sin((2*pi*(exp(t*x) - 1))/(exp(t) - 1)).*(cos((2*pi*(exp(s*y) - 1))/(exp(s) - 1)) - 1).^2)/(2*pi*(exp(t) - 1)^3) + ...
            (s*t^2*exp(s*y + t*x).*sin((2*pi*(exp(s*y) - 1))/(exp(s) - 1)).*sin((2*pi*(exp(t*x) - 1))/(exp(t) - 1)))/((exp(s) - 1)*(exp(t) - 1)) - ...
            (t*exp(t*x).*sin((2*pi*(exp(t*x) - 1))/(exp(t) - 1)).*(cos((2*pi*(exp(s*y) - 1))/(exp(s) - 1)) - 1).*((s^2*exp(2*s*y).*cos((2*pi*(exp(s*y) - 1))/(exp(s) - 1)).*(cos((2*pi*(exp(t*x) - 1))/(exp(t) - 1)) - 1))/(exp(s) - 1)^2 + ...
            (t^2*exp(2*t*x).*cos((2*pi*(exp(t*x) - 1))/(exp(t) - 1)).*(cos((2*pi*(exp(s*y) - 1))/(exp(s) - 1)) - 1))/(exp(t) - 1)^2 + ...
            (s^2*exp(s*y).*sin((2*pi*(exp(s*y) - 1))/(exp(s) - 1)).*(cos((2*pi*(exp(t*x) - 1))/(exp(t) - 1)) - 1))/(2*pi*(exp(s) - 1)) + ...
            (t^2*exp(t*x).*sin((2*pi*(exp(t*x) - 1))/(exp(t) - 1)).*(cos((2*pi*(exp(s*y) - 1))/(exp(s) - 1)) - 1))/(2*pi*(exp(t) - 1))))/(2*pi*(exp(t) - 1)) + ...
            (2*pi*s*t^2*exp(s*y + t*x).*exp(t*x).*cos((2*pi*(exp(t*x) - 1))/(exp(t) - 1)).*sin((2*pi*(exp(s*y) - 1))/(exp(s) - 1)))/((exp(s) - 1)*(exp(t) - 1)^2) - ...
            (s^2*t*exp(t*x).*exp(2*s*y).*sin((2*pi*(exp(s*y) - 1))/(exp(s) - 1)).^2.*sin((2*pi*(exp(t*x) - 1))/(exp(t) - 1)).*(cos((2*pi*(exp(t*x) - 1))/(exp(t) - 1)) - 1))/(2*pi*(exp(s) - 1)^2*(exp(t) - 1));
        r(:,2) = nu*((s^2*t*exp(s*y).*exp(t*x).*sin((2*pi*(exp(s*y) - 1))/(exp(s) - 1)).*sin((2*pi*(exp(t*x) - 1))/(exp(t) - 1)))/((exp(s) - 1)*(exp(t) - 1)) + ...
            (2*pi*s^2*t*exp(t*x).*exp(2*s*y).*cos((2*pi*(exp(s*y) - 1))/(exp(s) - 1)).*sin((2*pi*(exp(t*x) - 1))/(exp(t) - 1)))/((exp(s) - 1)^2*(exp(t) - 1))) - ...
            nu*((3*t^3*exp(2*t*x).*cos((2*pi*(exp(t*x) - 1))/(exp(t) - 1)).*(cos((2*pi*(exp(s*y) - 1))/(exp(s) - 1)) - 1))/(exp(t) - 1)^2 + ...
            (t^3*exp(t*x).*sin((2*pi*(exp(t*x) - 1))/(exp(t) - 1)).*(cos((2*pi*(exp(s*y) - 1))/(exp(s) - 1)) - 1))/(2*pi*(exp(t) - 1)) - ...
            (2*pi*t^3*exp(3*t*x).*sin((2*pi*(exp(t*x) - 1))/(exp(t) - 1)).*(cos((2*pi*(exp(s*y) - 1))/(exp(s) - 1)) - 1))/(exp(t) - 1)^3) + ...
            (s^3*exp(2*s*y).*sin((2*pi*(exp(s*y) - 1))/(exp(s) - 1)).^2.*(cos((2*pi*(exp(t*x) - 1))/(exp(t) - 1)) - 1).^2)/(4*pi^2*(exp(s) - 1)^2) + ...
            (s^3*exp(3*s*y).*cos((2*pi*(exp(s*y) - 1))/(exp(s) - 1)).*sin((2*pi*(exp(s*y) - 1))/(exp(s) - 1)).*(cos((2*pi*(exp(t*x) - 1))/(exp(t) - 1)) - 1).^2)/(2*pi*(exp(s) - 1)^3) + ...
            (s^2*t*exp(s*y + t*x).*sin((2*pi*(exp(s*y) - 1))/(exp(s) - 1)).*sin((2*pi*(exp(t*x) - 1))/(exp(t) - 1)))/((exp(s) - 1)*(exp(t) - 1)) - ...
            (s*exp(s*y).*sin((2*pi*(exp(s*y) - 1))/(exp(s) - 1)).*(cos((2*pi*(exp(t*x) - 1))/(exp(t) - 1)) - 1).*((s^2*exp(2*s*y).*cos((2*pi*(exp(s*y) - 1))/(exp(s) - 1)).*(cos((2*pi*(exp(t*x) - 1))/(exp(t) - 1)) - 1))/(exp(s) - 1)^2 + ...
            (t^2*exp(2*t*x).*cos((2*pi*(exp(t*x) - 1))/(exp(t) - 1)).*(cos((2*pi*(exp(s*y) - 1))/(exp(s) - 1)) - 1))/(exp(t) - 1)^2 + ...
            (s^2*exp(s*y).*sin((2*pi*(exp(s*y) - 1))/(exp(s) - 1)).*(cos((2*pi*(exp(t*x) - 1))/(exp(t) - 1)) - 1))/(2*pi*(exp(s) - 1)) + ...
            (t^2*exp(t*x).*sin((2*pi*(exp(t*x) - 1))/(exp(t) - 1)).*(cos((2*pi*(exp(s*y) - 1))/(exp(s) - 1)) - 1))/(2*pi*(exp(t) - 1))))/(2*pi*(exp(s) - 1)) + ...
            (2*pi*s^2*t*exp(s*y + t*x).*exp(s*y).*cos((2*pi*(exp(s*y) - 1))/(exp(s) - 1)).*sin((2*pi*(exp(t*x) - 1))/(exp(t) - 1)))/((exp(s) - 1)^2.*(exp(t) - 1)) - ...
            (s*t^2*exp(s*y).*exp(2*t*x).*sin((2*pi*(exp(s*y) - 1))/(exp(s) - 1)).*sin((2*pi*(exp(t*x) - 1))/(exp(t) - 1)).^2.*(cos((2*pi*(exp(s*y) - 1))/(exp(s) - 1)) - 1))/(2*pi*(exp(s) - 1)*(exp(t) - 1)^2);
    end
    function r = omega(p)
        x = p(:,1); y = p(:,2);
        r = (s^2*exp(2*s*y).*cos((2*pi*(exp(s*y) - 1))/(exp(s) - 1)).*(cos((2*pi*(exp(t*x) - 1))/(exp(t) - 1)) - 1))/(exp(s) - 1)^2 + ...
            (t^2*exp(2*t*x).*cos((2*pi*(exp(t*x) - 1))/(exp(t) - 1)).*(cos((2*pi*(exp(s*y) - 1))/(exp(s) - 1)) - 1))/(exp(t) - 1)^2 + ...
            (s^2*exp(s*y).*sin((2*pi*(exp(s*y) - 1))/(exp(s) - 1)).*(cos((2*pi*(exp(t*x) - 1))/(exp(t) - 1)) - 1))/(2*pi*(exp(s) - 1)) + ...
            (t^2*exp(t*x).*sin((2*pi*(exp(t*x) - 1))/(exp(t) - 1)).*(cos((2*pi*(exp(s*y) - 1))/(exp(s) - 1)) - 1))/(2*pi*(exp(t) - 1));
    end
    function r = diffCo(p)
        x = p(:,1); y = p(:,2);
        r = nu*ones(size(p,1),1);
    end

end